# Generated by Django 3.1.3 on 2021-02-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210203_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='timezone',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
