# Generated by Django 3.1.3 on 2021-02-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_city_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='cityNameENG',
            field=models.CharField(default='', max_length=85),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='countryENG',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
